# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Adding external jars..."
    - mvn install:install-file -Dfile=lib/lcd-1.0.jar -DgroupId=se.hirt.pi -DartifactId=lcd -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true
    - mvn install:install-file -Dfile=lib/bluecove-2.1.1-SNAPSHOT.jar -DgroupId=com.bluecove -DartifactId=bluecove -Dversion=2.1.1-SNAPSHOT -Dpackaging=jar -DgeneratePom=true
    - mvn install:install-file -Dfile=lib/bluecove-emu-2.1.1-SNAPSHOT.jar -DgroupId=com.bluecove -DartifactId=bluecove-emu -Dversion=2.1.1-SNAPSHOT -Dpackaging=jar -DgeneratePom=true
    - mvn install:install-file -Dfile=lib/bluecove-gpl-2.1.1-SNAPSHOT.jar -DgroupId=com.bluecove -DartifactId=bluecove-gpl -Dversion=2.1.1-SNAPSHOT -Dpackaging=jar -DgeneratePom=true
    - echo "Compiling the code..."
    - mvn package -Dmaven.test.skip=true
    - echo "Compile complete."
  artifacts:
    paths:
      - target/tcuwifi.jar
